# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fetch_client2' do

  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for fetch_client2
  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Messaging', '~> 5.20.1'
  
  target 'fetch_client2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fetch_client2-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fetch_client2-tvOS

  target 'fetch_client2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
